/**
 * Custom type aliases for Supabase RPC return types
 *
 * This file exists separately from supabase.ts because that file is
 * auto-generated by `npm run gen:types` and would overwrite these aliases.
 */

import type { Database } from './supabase';

// Queue RPC types
// Override cancelled_at to be nullable (auto-generated type incorrectly says string)
type GetQueueRowBase = Database['public']['Functions']['get_queue']['Returns'][number];
export type GetQueueRow = Omit<GetQueueRowBase, 'cancelled_at'> & { cancelled_at: string | null };
export type GetQueueStatsRow = Database['public']['Functions']['get_queue_stats']['Returns'][number];

// Staff RPC types
export type GetStaffTimesRow = Database['public']['Functions']['get_staff_times']['Returns'][number];
export type GetStaffTimesDetailRow = Database['public']['Functions']['get_staff_times_detail']['Returns'][number];

// Order RPC types
export type GetCompleteRow = Database['public']['Functions']['get_complete']['Returns'][number];
export type FindOrderRow = Database['public']['Functions']['find_order']['Returns'][number];

// Settings RPC types
export type GetSettingsRow = Database['public']['Functions']['get_settings']['Returns'][number];
