/**
 * Custom type aliases for Supabase RPC return types
 *
 * This file exists separately from supabase.ts because that file is
 * auto-generated by `npm run gen:types` and would overwrite these aliases.
 */

import type { Database } from './supabase';

// Queue RPC types
export type GetQueueRow = Database['public']['Functions']['get_queue']['Returns'][number];
export type GetQueueStatsRow = Database['public']['Functions']['get_queue_stats']['Returns'][number];

// Staff RPC types
export type GetStaffTimesRow = Database['public']['Functions']['get_staff_times']['Returns'][number];
export type GetStaffTimesDetailRow = Database['public']['Functions']['get_staff_times_detail']['Returns'][number];

// Order RPC types
export type GetCompleteRow = Database['public']['Functions']['get_complete']['Returns'][number];
export type FindOrderRow = Database['public']['Functions']['find_order']['Returns'][number];

// Settings RPC types
export type GetSettingsRow = Database['public']['Functions']['get_settings']['Returns'][number];
